### ISSUE TITLE
handsome 7 中出现宽屏首页头图不显示

### ISSUE THREAD

**Issue by Woooooow-Pro** [Sanakey/KirinShiKi#2]
如图所示，13寸 macpro, chrome 游览器（然而屏幕缩小后头图又会显示，嘤嘤嘤）

![image](https://user-images.githubusercontent.com/49100371/88871462-84769c00-d24a-11ea-8935-a703dba77244.png)

**Comment by Sanakey** [comment]
还不清楚是不是handsome 7更新后带来的问题，暂时还没去测，可以的话，方便给个博客链接吗? 我有时间查查看。

**Comment by broodunivermonster** [comment]
blog.guanduochen.xyz

And 点击文章会爆炸（落泪）

**Comment by Woooooow-Pro** [comment]
> 还不清楚是不是handsome 7更新后带来的问题，暂时还没去测，可以的话，方便给个博客链接吗? 我有时间查查看。

blog.guanduochen.xyz

And 点击文章会爆炸（落泪）

**Comment by Sanakey** [comment]
我大概看了下，这次7版本变化有点大。首页文章不仅改了样式类名，甚至连html结构都发生了较大变化。目前插件无法正常食用是肯定的了，建议关闭当前插件，等我以后更新插件了再用，或者使用7.0以下的handsome。

**Comment by Sanakey** [comment]
今天我在本地更新了handsome 7.1，发现插件是可以正常使用的，不知道是不是你魔改过或者改了什么特殊设置，还是使用了一些其他插件发生了冲突，导致你的文章html结构和css样式名发生了变化。

**Comment by JeffersonQin** [comment]
今天我试了一下 查出原因应该是要调整到大头图模式才行。
